# Generated by Django 3.0.3 on 2020-04-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200419_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='summary',
            field=models.TextField(help_text='Summarize the genre.', max_length=1000, null=True),
        ),
    ]
