# Generated by Django 3.0.3 on 2020-04-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_genre_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='summary',
            field=models.TextField(blank=True, help_text='Summarize the genre.', max_length=1000, null=True),
        ),
    ]
